### PR TITLE
Welcome_page (GCI-37)

### PR DESCRIPTION
**Pull request by m3ghnaa**

### CODE REVIEW

**Comment by elliottwilliams** [comment]
This is a pretty good start. Rather than using your customized button, could you use a large bootstrap primary button, similar to what's used elsewhere on the site?

Check the bootstrap button syntax here: http://getbootstrap.com/css/#buttons-sizes

Another thing you can do with this button is link it like this:

``` html
<a href="...">
    <button type="button" class="btn btn-primary btn-lg">Button Text Here</button>
</a>
```

This will keep the button from having orange link text, and instead make the entire button the link.

Thanks!

**Comment by m3ghnaa** [comment]
Okay, Thanks!
I have made the changes.

**Comment by elliottwilliams** [comment]
Thanks! A couple other things:
- It looks like your centered "Start making connections" button just has a big `margin-left` on it. Since screen sizes are all different, could you center-align the element using CSS? Maybe try the [Bootstrap block center class](http://getbootstrap.com/css/#helper-classes-center), as well.
- The jumbotron text size is appearing in the "Need help?" entry below? Are you forgetting to close an HTML tag somewhere?

I'll give you some more time to work on this. Good luck!

**Comment by m3ghnaa** [comment]
Thank you again! :)
I have made the changes.

**Comment by elliottwilliams** [comment]
Thanks for fixing that up. Nice work!

**Comment by robbyoconnor** [comment]
@meghna97, if it isn't too much and no rush but could you please rebase your commits and squash them into one commit -- it's neater. Here's how to do this: 

_git rebase -i HEAD~5_
change "pick" to  "squash" for all but the first commit 
save the file and close it 
You need to force this -- one of the rare cases where force-pushing is okay: _git push origin welcome -f_

**Comment by robbyoconnor** [comment]
See [this pull request](https://github.com/meghna97/openmrs-contrib-id/pull/2) and merge it...your change will reflected here in the way I am looking for :)

**Pull request closed without merging**
