### PR TITLE
GCI-34 - ID Dashboard UI Revamp - Sign up page

### PR DESCRIPTION
**Pull request by andreiamini**
This is a redesigned sign up page for OpenMRS ID 

Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/5145706734026752

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Awesome! Could you try doubling the width of those input fields? I feel like the widget is a little on the empty side right now. When we make some of the site-level layout changes in the new design, we will shrink the page width, which will help, but could you try doubling the width of those form fields?

Just add new commits to the branch in the pull request and they'll come in automatically.

**Comment by andreiamini** [comment]
@elliottwilliams Doubled the width of the input fields

**Comment by elliottwilliams** [comment]
Could you also double the width of the `.two-up` fields? (on the sign up page, this is the first/last name field). You probably need to double them and then increase them by 2px or so so that they line up with the other fields.

**Comment by andreiamini** [comment]
Doubled the width of the  <code>.two-up</code> fields.

**Comment by elliottwilliams** [comment]
Ok, thanks! Approving.

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by andreiamini** [comment]
Could you perhaps accept the task on Melange? Thanks.

**Comment by dkayiwa** [comment]
@robbyoconnor what do you think about this pull request?

**Pull request closed without merging**
