### PR TITLE
GCI 36 - Reset password page Revamp

### PR DESCRIPTION
**Pull request by Izaron**
Ticket: https://issues.openmrs.org/browse/GCI-36
Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/5166893270827008

What about the form with the "panel-footer"? I think it looks like a good variant!

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Yeah, I like the use of `panel-footer`, it's nice to have a visual distinction between the form contents and the submission button area.

Could you apply similar style changes to `reset-private.ejs`? It's a very similar page, but the one users see when they follow the reset password link that's emailed to them.

**Comment by Izaron** [comment]
No problem with reset-private.ejs, thanks for help :)

**Comment by elliottwilliams** [comment]
I'm seeing some visual problems on reset-private:
screen shot 2014-12-26 at 13 14 57

Could you try using [bootstrap form styling](http://getbootstrap.com/css/#forms) on both pages? We're moving away from the `.field` styles used on forms to just using bootstrap. Switching to bootstrap here would get rid of that labeling problem.

Thanks!

**Comment by Izaron** [comment]
@elliottwilliams 
All done and verified. Tell me, what is missing? Gone yellow lights in the description, and I do not know how to fix it is... Should I use background-color for span as in:
http://www.htmlgoodies.com/tutorials/html_401/article.php/3479661
or not? And if yes, where the style .less file for reset-private.ejs?

**Comment by elliottwilliams** [comment]
It doesn't seem to me like anything is missing, what are you referring to? I think it's all good. The field descriptions are always visible, but in forms like these I think that makes sense—there's no reason to hide information from the user until they focus in on a form field.

**Comment by robbyoconnor** [comment]
I merged this with modifications in [f99ab7b](https://github.com/openmrs/openmrs-contrib-id/commit/f99ab7ba9c4f7e9a9243905d96b60e1e0488dc5f)

**Pull request closed without merging**
