### PR TITLE
GCI-37 - Welcome page Revamp

### PR DESCRIPTION
**Pull request by Izaron**
Ticket: http://issues.openmrs.org/browse/GCI-37
Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/5668125081075712

This is my version of the Welcome page
It looks like this:
welcome

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Great start. Rather than use `style` attributes on the HTML tags here, it's generally our convention in this project to style these elements in a .less stylesheet. Could you move your styles from the elements here to a .less file?

I think the best thing to do would be to create a file `resource/less/welcome.less` for these element styles, then import them into style.less, which will cause them to be compiled and loaded into the page.

**Comment by Izaron** [comment]
@elliottwilliams 
Ok, I done it! Please review it :)

**Comment by elliottwilliams** [comment]
Sweet. One more thing: can you remove the `<center>` tag and implement it using CSS? `<center>` is deprecated in HTML5, and since the ID Dashboard claims html5, we shouldn't use it. You should be able to do it with `text-align: center` and possibly `margin-left` and `margin-right` set to `auto`.

More info: https://stackoverflow.com/questions/1798817/why-is-the-center-tag-deprecated-in-html

**Comment by Izaron** [comment]
@elliottwilliams 
Done it

**Comment by elliottwilliams** [comment]
So close! Could you please move that styling to `welcome.less`, for the same reasons as above?

**Comment by elliottwilliams** [comment]
Thanks!

**Comment by elliottwilliams** [comment]
> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Pull request closed without merging**
