### PR TITLE
GCI-33 USER INTERFACE: ID DASHBOARD UI REVAMP - SITE FOOTER

### PR DESCRIPTION
**Pull request by chaityabshah**
https://issues.openmrs.org/browse/GCI-33 Dashboard UI Revamp - Footer

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Looks good, thank you! Could you send me a link to your Melange task?

**Comment by chaityabshah** [comment]
Here's the [Melange Task](https://www.google-melange.com/gci/task/view/google/gci2014/5125590449389568)

**Comment by robbyoconnor** [comment]
@chaityabshah -- resolve merge conflicts and then rebase to squash them into one commit.

**Comment by robbyoconnor** [comment]
There are conflicts because these changes were made already and merged in #20 and such I am closing this...

**Pull request closed without merging**
