### PR TITLE
Implement GCI-34: Sign up page

### PR DESCRIPTION
**Pull request by Undo1**
This implements [GCI-34](https://issues.openmrs.org/browse/GCI-34), updating the design and copy of the sign up page. 

Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/5557050314588160.

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Could you add a little extra padding to the form? I want to avoid the ReCAPTCHA content flowing outside the form panel:

openmrs_id_-_sign_up

When you increase the form size, I also think it'd make sense to give the "Join the Community" button a little more vertical margin.

But other than that, strong work!

**Comment by Undo1** [comment]
@elliottwilliams, added a larger vertical padding to the form and moved the button down. I also added a white background to the captcha view, in case it ever decides to escape again.

**Comment by elliottwilliams** [comment]
Okay, great! I'll approve your task in Melange.

Since we have multiple students working on each UI task, I'm not going to merge your code just yet. I want to figure out a way for everyone to be able to submit a pull request, but in a way that won't overwrite other students' work. So for now I'll leave this unmerged—once we figure out how to handle this I will let you know.

**Comment by dkayiwa** [comment]
@robbyoconnor what do you think of this pull request?

**Pull request closed without merging**
