### PR TITLE
Added error modal window on signup server error

### PR DESCRIPTION
**Pull request by diospark**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
It's about 80% there -- is it possible to make the button color match (e.g., be Orange) 
image

I'd also like the boxed text to be on one line -- it should also say to email helpdesk -- currently I get that code but I have no idea what to do with it. Link to https://om.rs/helpdesk

**Comment by robbyoconnor** [comment]
I can fix all of this on my end -- it's good enough for me to merge -- this stuff is minor -- just wanted to bring it up.

**Comment by robbyoconnor** [comment]
I addressed the issues locally -- so no need to take action

**Comment by robbyoconnor** [comment]
The changes are currently merged in the master of my fork -- I'm holding off on pushing to this repo but will likely do so soon...As such I'm closing this.

**Comment by Plypy** [comment]
The error message could provide more information for users, not only a confusing error track id.

**Comment by robbyoconnor** [comment]
@Plypy, I actually fixed this in the master branch while I was merging this. We don't wanna show the error to the user -- just that something went wrong and to email the helpdesk. As the PR was initially, you're right it's very confusing to me...what this means.

**Comment by robbyoconnor** [comment]
Merged in fccf2b7, slight fix to styling and wording in d002671.

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67odt-ko&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=kjVo3Nwu&invitationId=6130897023412559873








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67odt-ko&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFA3KnlmYWQtgAAAVRVSclxeCxJ9dM8k1uz-cFTjW0LoJfJlpxtWFyqcxVpTnS1VDRJ3Slo4Qz_Rotkugl5mpQvjl7oK43n98aSM8VU8hpUvDPWz4VVnoNIQE6t3FreIDA6V8mvui1EC9edjf6bTD9Qv9qaYRxFxMTlUiVA-sVIvU7zi98qboQzCw8Kbj5nJQfV&eid=0-ini67odt-ko


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67odt-ko&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
