### PR TITLE
[GCI-42] Edit email addresses widget

### PR DESCRIPTION
**Pull request by SquidDev**
[From this issue](http://issues.openmrs.org/browse/GCI-42). I hope it looks ok.

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Looks pretty nice! One suggestion:
- Remove the little reveal animation on the "Add another" form. I don't feel like it really makes the form easier to understand, so all it does (in my opinion) is add transition time. My philosophy with animations is that they should probably only exist if they make things easier to understand ;-)

Thanks for your work!

**Comment by SquidDev** [comment]
Thanks for the response.
I've removed the animation, and switched to using Javascript instead of Bootstrap's collapse plugin.

**Comment by elliottwilliams** [comment]
Awesome, thanks! I guess it didn't occur to me that you were using Bootstrap collapse. 

If you want to go back to using collapse (and thus not having to add stuff to `omrsid.js`), you could use collapse and add this block to a new LESS file called `overrides.less`:

``` css
.collapsing {
    -webkit-transition: none;
    transition: none;
}
```

(via https://stackoverflow.com/questions/13119912/disable-bootstraps-collapse-open-close-animation)

This might be a little simpler than having to write custom code, plus it would disable the collapse animation in general.

Regardless I'll accept this task but that's just a suggesting if you want to go above and beyone :-)

**Comment by SquidDev** [comment]
I looked at that, however I had two issues:
- Bootstrap still [waits for the transition](https://github.com/twbs/bootstrap/blob/master/js/collapse.js#L33) to occur, even when it is disabled with CSS. This means there is a delay before the `shown.bs.collapse` event is fired, which means auto-focusing a field has a delay. (Using `show.bs.collapse` didn't focus the field at all).
- I had to add Javascript so the field is auto focused, so I thought using `.toggle()` would add more flexibility.

The alternative I thought of was using something like [this](http://stackoverflow.com/a/23921617/1447657):

``` javascript
$('[data-toggle=collapse]').on('shown.bs.modal', function() {
  $(this).find('[autofocus]').focus();
});
```

**Pull request closed without merging**
