### PR TITLE
 GCI-31 USER INTERFACE: ID DASHBOARD UI REVAMP - NAVIGATION BAR

### PR DESCRIPTION
**Pull request by itatriev**
_I've used breadcrumb class as @robbyoconnor_ suggested. <--- old description

New Navigation Bar -->

navbar1
================================== **Mobile**==========================================
navbar2

### CODE REVIEW

**Comment by robbyoconnor** [comment]
You misunderstood what I said: 

You should use the [Bootstrap Navbar](http://getbootstrap.com/components/#navbar)  and  [Bootstrap Breadcumbs](http://getbootstrap.com/components/#breadcrumbs) together.  The point is to have a seamless experience where i can backtrack if needed...you don't have that. You still need the navbar -- which you don't have at all. 

Maybe take away the breadcrumbs for now,..you don't seem to understand their purpose (that's ok!)

**Comment by robbyoconnor** [comment]
Good job

**Comment by elliottwilliams** [comment]
> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by robbyoconnor** [comment]
#48 is also part of this...I guess two alternatives...I cannot find a task linked to #48 and quite frankly I prefer #48 anyways!

**Comment by robbyoconnor** [comment]
I am reopening this upon farther consideration...We will take #48 into consideration, in addition to this.  My Rationale: I checked responsiveness and #48 was not that good as far as responsiveness is concerned.

**Pull request closed without merging**
