### PR TITLE
Sign up Page Revamp

### PR DESCRIPTION
**Pull request by chaityabshah**
[GCI-34](https://issues.openmrs.org/browse/GCI-34)
[Melange task](https://www.google-melange.com/gci/task/view/google/gci2014/4702538855088128)

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Do you have a claim on this task in Melange? The task you've linked to isn't yours, and I don't see anything for GCI-34 you are assigned to.

**Comment by chaityabshah** [comment]
Whoops, linked to wrong GCI-34 task. Fixed.

**Comment by elliottwilliams** [comment]
Got it. FYI, one of the OpenMRS mentors _needs_ to grant your claim request before you are allowed to start work on the task. This is to keep GCI as fair as possible.

Thanks, though. Once you finish any remaining work and put the task in "Needs Review" I will review your code.

**Comment by chaityabshah** [comment]
Right, sorry about that. Thanks.

**Comment by elliottwilliams** [comment]
Cool, thanks!

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by dkayiwa** [comment]
@robbyoconnor @elliottwilliams what do you think about this pull request?

**Pull request closed without merging**
