### PR TITLE
GCI-34: Sign Up Page (V2)

### PR DESCRIPTION
**Pull request by glowcone**
Updated with changes. Deleted the sign-up-page branch.

screen shot 2014-12-06 at 4 42 51 pm

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Looks great! Just one thing I noticed: the failure text (the text that shows up if there's a form field error) is slightly messed up on the name and email fields (the fields that don't have a description). You can check this by submitting a blank signup form.

To fix this, could you change `<span class="failtext">` to `<span class="failtext description">` on the name and email fields? Then, remove the background color that gets applied in the description `.description` selector—it's not needed anymore and will conflict with the failtext colors in this case.

That's it! Really sorry for taking a long time on this pull request—I was offline most of this weekend

**Comment by glowcone** [comment]
Done!

screen shot 2014-12-09 at 4 05 16 pm

**Comment by elliottwilliams** [comment]
Awesome, thanks!

**Comment by elliottwilliams** [comment]
> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by dkayiwa** [comment]
@robbyoconnor @elliottwilliams what do you think about this pull request?

**Pull request closed without merging**
