### PR TITLE
GCI: Sign in page

### PR DESCRIPTION
**Pull request by glowcone**
GCI task sign in page. 
The other commits can be ignored because they were for the previous task. I reverted files except for signin.ejs back to origin.

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Thanks! A couple things I noticed:
- the "username" field is causing the "check if this user exists" JS code to run, which is definitely not what we want (I should not see "elliott is already taken" when I'm trying to sign in!). You could change the way this code works in omrsid.js (you might just customize the jQuery selector), or you could change the placeholder text for the username field to "OpenMRS ID" or something like that
- your text fields look really small, and I realized this was because you're using `.two-up` fields (which are half size of normal fields). did you intend to do this? I think they should definitely be normal fields

Work on these two things, and then you're good to go.

**Comment by glowcone** [comment]
whoops, pushed to wrong branch. Fixing...

**Comment by elliottwilliams** [comment]
Awesome, thank you for your work!

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by robbyoconnor** [comment]
It would be helpful (for the sake of commit history) if you rebased to squash your commits into one. 

**git rebase -i HEAD~7**

and replace "pick" with squash for all but the first and then save the file and close it

Edit the commit to be just one succinct message describing your work 
After that do: **git push -f origin sign-in-page**. This would be helpful to us. I am in the process of gathering the submissions.

**Comment by robbyoconnor** [comment]
@st3phan1e I rebased for you in [this pull request](https://github.com/st3phan1e/openmrs-contrib-id/pull/1)

**Comment by glowcone** [comment]
Merged.

**Pull request closed without merging**
