### PR TITLE
ID-68 / GCI-31 (updating Navigation bar)

### PR DESCRIPTION
**Pull request by m3ghnaa**
Modified navbar view as per the wireframe - (https://issues.openmrs.org/secure/attachment/42375/id-wireframe-2.png)

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Cool, thanks! Instead of having the nav bar span across the entire page's width, could you use a [bootstrap grid element](http://getbootstrap.com/css/#grid), so that the nav bar fits in with the rest of the page's width?

The code would be something like this:

``` html
<div class="col-md-10 col-md-offset-1">
  <ul id="user-nav">
    ...  
  </ul>
</div>
```

**Comment by elliottwilliams** [comment]
Thanks! Accepting your task. 

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by m3ghnaa** [comment]
The last one was accidental. I don't know how to undo it.

**Comment by elliottwilliams** [comment]
You need to undo commit 7dde475? See https://stackoverflow.com/questions/22682870/git-undo-pushed-commits on how to use `git revert`

**Pull request closed without merging**
