### PR TITLE
[ID-86] Upgrading to reCAPTCHA 2.0

### PR DESCRIPTION
**Pull request by Plypy**
In this PR, I replaced the old reCAPTCHA module with my own implementation to work with reCAPTCHA2.0, updated the style sheets and 'formatted' some sources.

### CODE REVIEW

**Comment by ghost** [comment]
:star2: Thanks for leading this!

**Comment by robbyoconnor** [comment]
:star2: :star2: :star2: :star2: :star2:  Great job!!! :heart:

**Comment by robbyoconnor** [comment]
Does not run...
ssh nitrious_495

**Comment by Plypy** [comment]
Sorry... I forgot to mention that you need to run `npm install` first, as you see, I've added the package request.

**Comment by Plypy** [comment]
There are some conflicts in the `package.json`, I'm trying to fix it.

**Comment by Plypy** [comment]
During testing... I found that we should upgrade our node, as the npm itself won't support the 0.8.x tree anymore. And the older version npm comes along with node 0.8.x won't support `^` used in our package.json, and brings other weird things. So to ease the pain, we'd better just upgrade the node to 0.10.x, as said before Dashboard should be compatible with newer node.

> Test: Run node -v. The version should be higher than v0.10.32.

**Comment by Plypy** [comment]
You can install the dependency by `npm install --no-shrinkwrap`. I'll deal with the package updating later.

Also, note that I haven't added the `label` and `failtext` for it. So the preceding text `Captcha` will be gone, and if the user haven't passed the reCaptcha, there will be no hint.

You can customize these you own.

**Comment by Plypy** [comment]
@robbyoconnor  I've added a flash message for the validator, it will pop out everytime when the validation fails.

What do you think of this?

image

**Comment by ghost** [comment]
Is this message for when the captcha is not completed? If so let's use the
language "Please let us know you're human."

**Comment by Plypy** [comment]
No, it's for general purpose. Shall I work out some unique message for the
Captcha?

**Comment by ghost** [comment]
If for general purpose I'd say something like: "Please complete all the
items and try again."

**Comment by Plypy** [comment]
May be "verify all the items"?

**Comment by ghost** [comment]
Please remind me. Is there any highlight or visual indication of missing or
incorrect fields?

If yes, "Please check the highlighted items and try again."

If no, "Please review all items and try again."

**Comment by Plypy** [comment]
Anyway, this message is just a compromise. As it is kind of hard to customize the noCaptcha, and use the old way by showing the hint message right by the input box.

And you can easily change the messages to what you like.

**Comment by Plypy** [comment]
> Please remind me. Is there any highlight or visual indication of missing or
> incorrect fields?

This is what it looks like now, when all the items are missing, these messages are independently from each other.

image

So I guess "Please review all items and try again" is preferred.

**Comment by ghost** [comment]
Yes sounds good. Thank you!!

**Comment by robbyoconnor** [comment]
I'm going to be upgrading all forms to bootstrap -- so we can add a better visual indicator and all errors appear in the flash message.

**Pull request merged**
