### PR TITLE
changed ldap.isDisabled logic for ID-82

### PR DESCRIPTION
**Pull request by diospark**
I've been changed ldap.isDisabled method logic. Now for disabling ldap user can set `ldap.enbled` to false.
`conf.example.js` was updated with option `ldap.enabled`
also Readme for installing was updated.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Edit: I'm going to test this in a few hours when I wake up. I was reading this too fast -- and my brain isn't working apparently.

**Comment by robbyoconnor** [comment]
Add tests to confirm this works...always have tests.  Would also be nice if there was a console log message that told me "ldap is disabled" -- use your judgement on the wording.

**Comment by robbyoconnor** [comment]
I'll have to manually merge this by hand -- things got a bit diverged due to me rebasing -- which is REALLY bad to do and I uh see that now -- all branches are currently affected. 

I ran your tests -- They are REALLY complete. Great job. I'll manually merge this by hand and review your changes -- I see no reason to not merge this...I will close the ticket after I merge this.

**Comment by robbyoconnor** [comment]
Okay here's what you need to do -- I'm going to merge what i have merged right now manually -- Did you test this beyond writing tests to check if your config settings works? 

Using 7aec6a9 as a base, fix it so that users can sign up and login with ldap disabled. and make a new PR.

**Comment by robbyoconnor** [comment]
I reverted your changes -- I need to do more testing...it's weird...but will ping you when it's ready -- I'm just getting the tests passing in the current tree.

**Comment by robbyoconnor** [comment]
Okay, so df59c1c has the current state -- it's nowhere near ready for merge -- but it's a starting offpoint that has a clean merge point When you are ready -- using that as a base, you should be able to do a PR against this branch -- but use my personal fork's branch for now. I am going to close this 

It's weird -- if ldap is disabled things work fine -- if ldap is enabled then all things go to hell and all tests start to fail and things break. 

In addition, things don't fully work. You need to test this better either manually or with unit/integration tests.  I merged in most of your code by hand. Please re-open a PR when you fix this ;)

**Comment by diospark** [comment]
OK Robert, thanks for your comments, I will notify you when I done this.

**Comment by robbyoconnor** [comment]
@diospark, hopefully you haven't started yet but if you did -- stop: 

```
git remote add robbyoconnor git@github.com:robbyoconnor/openmrs-contrib-id.git
```

Then (to get all remote branches): 

```
git fetch robbyoconnor
```

Then: 

```
git checkout merge-pr-73-ldap
```

 Work in that branch and use it for your PR -- it's fine -- it's a mergeable state where I won't encounter too many conflicts.

**Pull request closed without merging**
