### PR TITLE
Added recaptcha reset after validation error

### PR DESCRIPTION
**Pull request by mario-areias**
Fixes ID-143

### CODE REVIEW

**Comment by dkayiwa** [comment]
@robbyoconnor it's me again. What do you think of this? 😊

**Comment by robbyoconnor** [comment]
@dkayiwa, this is one project where you maybe shouldn't merge code. We have mention-bot so I will see it. No need to always mention me -- it's okay if it sits.

**Comment by dkayiwa** [comment]
@robbyoconnor yes sir! 😊

**Comment by robbyoconnor** [comment]
@mario-areias -- good work. Thank you so much

**Comment by robbyoconnor** [comment]
@mario-areias -- I'm not 100% thrilled since we're forcing users to solve the captcha AGAIN if they input invalid information.... The better way to do this would likely be [Invisible reCAPTCHA](https://developers.google.com/recaptcha/docs/invisible)

**Comment by robbyoconnor** [comment]
I merged it as it solves the immediate bug -- but..

**Comment by mario-areias** [comment]
@robbyoconnor when I tested in my machine, I didn't need to solve the captcha again. I just needed to click the checkbox again and the captcha was resolved. It did ask to solve after the third time the validation was wrong, but I think this is fair. Have you seen a different behaviour when you tested that?

**Comment by robbyoconnor** [comment]
I suppose -- I mean this is fixing a major blocker -- the current deployed version of ID Dashboard is crap. I mean it works...Invisible captcha might be more elegant but this works too.

**Pull request merged**
