### PR TITLE
GCI-38 User Interface: ID Dashboard UI Revamp - Edit account page

### PR DESCRIPTION
**Pull request by michalp2213**
Google Code-In task: http://www.google-melange.com/gci/task/view/google/gci2014/4940692979712000

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Thanks for your contribution, Michal.

First of all, are you intending to submit your widgets as additional tasks? Each widget on this page is its own GCI task, as the description on [GCI-38 indicated](https://issues.openmrs.org/browse/GCI-38) said. It's no problem, however I'll only review the work you did on the widget container page :) If you submit each widget under the other tasks I'll go over that code then :)

Anyways, this looks pretty good. A couple things to look at, though:
- Could you fix the padding at the top of the page? 
  screenshot from 2015-01-07 19 02 59
- Include a title, "Firstname Lastname's Profile" in the `headline` element on the page, like it's done on other areas of the site. We may get rid of the headline in the future, but for now templates should use it by default.

Thanks!

**Comment by michalp2213** [comment]
Ok, I fixed these issues. I hope everything is fine now. If widgets have their own tasks, I think I'll submit them. I didn't notice that I don't have to do them in this task :)

**Comment by elliottwilliams** [comment]
Alright, looks good. Thanks for your work!

**Comment by elliottwilliams** [comment]
Also, to get credit for your task, you'll need to re-claim your [Melange task](https://www.google-melange.com/gci/task/view/google/gci2014/4940692979712000) since you didn't mark "needs review" before it expired. No worries, just re-claim it, mark it as needs review and I'll accept it. Thanks!

**Comment by elliottwilliams** [comment]
Just closed the Melange task, so you're all set.

**Pull request closed without merging**
