### PR TITLE
GCI-41: edit basic account details widget

### PR DESCRIPTION
**Pull request by heidid**
GCI Ticket: https://issues.openmrs.org/browse/GCI-41

Since this is only a single widget, the Edit Profile page still looks unorganized. I also separated this widget code into a new file, edit-basic-details.ejs, as suggested on [ticket ID-76](https://issues.openmrs.org/browse/ID-76).

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Cool, good start! I'm happy to see someone working on the edit account page. 

I've got a few suggestions to improve this, what do you think?
- The "Need to change your password?" link should reveal the password-change form, which means the forms should be hidden by default. You'll need a little bit of javascript to do this. (You could embed your JS at the bottom of the page, or add it to `omrsid.js` — the project's frontend JS is a bit unorganized :laughing: )
- I think you should re-implement the forms without using the `field` class that applied all the old form stylings. You should try doing those form elements using [Bootstrap form components](http://getbootstrap.com/css/#forms). Remember that whatever you do, it should work at about a third of the width since that's how it'll look once the page layout is updated.
- Could you also just right-align the submit buttons like they are in the wireframe?

If you find you need to add some CSS, I would create a .less file `resource/less/profile.less`, and then import it into `style.less`.

**Comment by heidid** [comment]
Thanks for the feedback! I made your suggested updates.

**Comment by elliottwilliams** [comment]
Cool! Looks good. One bug I'm seeing is that clicking "Need to change your password?" jumps back up to the top of the page, which disrupts the experience. (it's telling the browser to navigate to the uri `#`). Could you use another method to keep this link from doing anything? Setting the href to `javascript:false` should do this but I'm not sure if that's the best practice for this.

**Comment by heidid** [comment]
Alright, I decided to use event.preventDefault() after reading [this StackOverflow thread](http://stackoverflow.com/questions/134845/href-attribute-for-javascript-links-or-javascriptvoid0).

**Comment by elliottwilliams** [comment]
Cool, thanks for your work!

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Pull request closed without merging**
