### PR TITLE
GCI-37 Welcome Page UI Revamp

### PR DESCRIPTION
**Pull request by chaityabshah**
[Melange Task](https://www.google-melange.com/gci/task/view/google/gci2014/5129744420962304)
Let me know if I can make this one better in any way... I'm not sure if removing the contents of headline will have any serious consequences... I went through all of the pages and it seemed fine.

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Cool, looking great. I think we'll need to figure out what to do with the headline on the welcome page...maybe there should be a way to tell the application to disable it on this specific page? Or we could just ditch the headline in the future, and just put `<h2>`s in each page template.

Regardless, that's more of a "high-level" design decision and doesn't directly affect your GCI task, so I'll accept it. Thanks for your help!

**Comment by elliottwilliams** [comment]
> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by chaityabshah** [comment]
I feel like the headline provides a good design, but if the avatar is going to stay next to the user's button in the top right of the page, it isn't needed anymore and we should switch over to hero-unit headings. But like you said, its a higher level decision, but thanks for letting me work on this :)

**Comment by elliottwilliams** [comment]
No problem, thanks for your input—we'll take this stuff into account when we finalize the design mid-January.

**Comment by chaityabshah** [comment]
Awesome, thanks!

**Pull request closed without merging**
