### PR TITLE
GCI-32 Site header/Session status revamp

### PR DESCRIPTION
**Pull request by chaityabshah**
[Melange task](https://www.google-melange.com/gci/task/view/google/gci2014/4589970647941120)

### CODE REVIEW

**Comment by elliottwilliams** [comment]
I think you could follow the wireframes better for this—it looks like you're trying to keep the old design around for this element. (and we're totally okay with throwing out any current designs :smile:)

Here's a reference to the wireframe, with the session status element in the top-right: https://wiki.openmrs.org/display/projects/ID+Dashboard+Wireframes#IDDashboardWireframes-Dashboard-Home/ExplorePage

Could you also do this without deleting the headline? I think it makes sense to remove the avatar from the headline, but not the whole element outright, since for now it makes a lot of pages title-less.

Thanks!

**Comment by chaityabshah** [comment]
Ah, sounds good. I'll make the changes.

**Comment by chaityabshah** [comment]
@elliottwilliams This commit should fix the issues with smaller computer screen sizes.... but when the user resizes the window, like everything else, the columns get a little bit messed up. Not sure if its possible to account for that.... Let me know if there's a way to add that and I'd be happy to :)

**Comment by elliottwilliams** [comment]
Sweet, thanks! Looks good for now. Maybe in the future we can have a sprint focusing on mobile-compatibility :-)

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Pull request merged**
