### PR TITLE
GCI-32 Site header and session status

### PR DESCRIPTION
**Pull request by itatriev**
[Melange Task](http://www.google-melange.com/gci/task/view/google/gci2014/4618480103981056)

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Can you right-align the text in the welcome message and the "Welcome, Firstname Lastname" text? Other than that, looks good to me!

**Comment by itatriev** [comment]
It's done!

**Comment by elliottwilliams** [comment]
Check the rendering issue I mentioned in the diff. I'll give you some more time to finish this up--thanks!

**Comment by itatriev** [comment]
I've fixed it and checked. All work just fine!

**Comment by elliottwilliams** [comment]
Great, thanks!

**Pull request closed without merging**
