### PR TITLE
GCI 32 - Site header and session status Revamp

### PR DESCRIPTION
**Pull request by Izaron**
Ticket: http://issues.openmrs.org/browse/GCI-32
Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/4603943317405696

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Did you look at the wireframes?

**Comment by Izaron** [comment]
@robbyoconnor
Yes, everything is done as in wireframes :)

**Comment by robbyoconnor** [comment]
Okay there were just misunderstandings on my part...going to let @elliottwilliams  comment but otherwise this looks ok to me.

**Comment by elliottwilliams** [comment]
Looks good...although it looks like you should give more space to the session status grid element. 

This is what I have in my instance:
screen shot 2014-12-27 at 17 50 53

I don't think "Welcome, Elliott Williams" should be two lines :-)

Thanks!

**Comment by elliottwilliams** [comment]
Hm, looking better although now it seems oddly distributed when displaying the signout text:

signout text

Could you see if you can find a good column setting that works for both? Remember that in Bootstrap you are working with 12-column-wide containers. You might also try shrinking down the number of columns the logo unit uses, as long as it's wide enough at all sizes.

**Comment by Izaron** [comment]
@elliottwilliams 
Ok, I fixed it!
Checked, double checked, triple checked, and so on :)

**Comment by elliottwilliams** [comment]
Yep, thanks for the extra checking. Looks great to me!

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Pull request closed without merging**
