### PR TITLE
GCI-34: Updated sign-up to wireframes layout

### PR DESCRIPTION
**Pull request by bucktower**
Here's a preview:
screenshotsnip

### CODE REVIEW

**Comment by bucktower** [comment]
Let me know if a Bootstrap panel would do better. Recently, I've been addicted to using wells over panels, and I thought this one could work?

**Comment by elliottwilliams** [comment]
I'm okay will wells, go for it :)

Couple things:
- could you hide the "country" field again by uncommenting that line of js? it's actually a [spam honeypot](http://solutionfactor.net/blog/2014/02/01/honeypot-technique-fast-easy-spam-prevention/) which we use as a 2nd-factor for spam prevention (unfortunately we still get spam accounts fairly regularly)
- for the fields that don't have a description, could you change the failtext span from `<span class="failtext">` to `<span class="description failtext">`? This should help the failure text render properly. You can check them by trying to submit an empty signup form, which should trigger failtext on every field
- could you also remove the background color on description text? it looks a little off in the well and it's shouldn't be needed in the stylesheet anymore (it's from an older time when description text wrapped over other description text in some special cases)

Thanks so much! Sorry I'm a little late on this review, I was offline most of the weekend

**Comment by glowcone** [comment]
Hey we are doing the same page! :P And they look the same too! Except I used panels...

**Comment by bucktower** [comment]
Twinsies :P! Ya, I've recently fallen in love with wells. IDK if I'm overdoing it right here, but I figured I mine as well do some stuff different since we're all essentially doing the same task. @elliottwilliams I'm working on it and shouldn't need an extension, I don't think.
BTW, @st3phan1e, [This guy](https://github.com/openmrs/openmrs-contrib-id/pull/19) is doing the same task too. I think Elliot's just trying to get the best of all 3.

**Comment by glowcone** [comment]
Haha I've never used wells before, they don't have it in Foundation.
Woah, another one doing the same task https://github.com/openmrs/openmrs-contrib-id/labels/gci-accepted
And I was thinking everyone had unique tasks... Maybe they are running out of ideas :sweat_smile:

**Comment by elliottwilliams** [comment]
Yeah, if you look at the issues in the [ID project](https://issues.openmrs.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=%22Epic+Link%22+%3D+ID-67+) we have quite a few, but we duplicated them in Melange so that one student can't rush through and complete all of them :) We want to give as many people a chance to participate, and give people a chance to get their design ideas out there.

**Comment by elliottwilliams** [comment]
In regards to your last commit, the only weird thing I'm seeing is that a horizontal line appears when you tab through the name and email address fields, even though there's no description texts. You might try working on the css (possible hiding `.description` when `.fail` is present or something) or adjusting the javascript that toggles those description fields

**Comment by bucktower** [comment]
Ok. After some consideration as to my options, I just put both classes into the same span. I'm not quite sure why I didn't do this with the other ones in the beginning, but I remember there being a reason. Bottom line: It should work now!

**Comment by elliottwilliams** [comment]
Looking great. Thank you!

> This task has been approved, but will not be merged into the repository until all GCI tickets in the ID Dashboard UI Revamp project have been submitted. We're doing this so that multiple students can submit their design implementation and we can select from the best collective implementation.

**Comment by bucktower** [comment]
Alright, thanks!

**Comment by dkayiwa** [comment]
@robbyoconnor @elliottwilliams what do you think about this pull request?

**Pull request closed without merging**
