### PR TITLE
ID-89: Refactor ldap.js and add tests

### PR DESCRIPTION
**Pull request by Plypy**
This PR improves the flow control, readability and efficiency of the antique source `ldap.js` as well as adds a unit tests for it.

Also, as the Dashboard is fully compatible with node 0.10.x, I upgraded the log4js to a newer version to get rid of the annoying `undefined` in testing.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Tests are failing for me; you're going to need to make a separate PR or maybe keep this one open and do add a fix for failing tests: 

```
$ npm test

> openmrsid@2.0.1 test /home/action/workspace/openmrs-contrib-id
> make test

node  test/runner.js

/home/action/workspace/openmrs-contrib-id/test/runner.js:21
  return _.endsWith(file, '.js') && file !== 'runner.js';
           ^
TypeError: Object function lodash(value) {
      // don't wrap if already wrapped, even if wrapped by a different `lodash` constructor
      return (value && typeof value == 'object' && !isArray(value) && hasOwnProperty.call(value, '__wrapped__'))
       ? value
       : new lodashWrapper(value);
    } has no method 'endsWith'
    at /home/action/workspace/openmrs-contrib-id/test/runner.js:21:12
    at Array.filter (native)
    at Object.<anonymous> (/home/action/workspace/openmrs-contrib-id/test/runner.js:20:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
make: *** [test] Error 8
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

It also no longer runs...

**Comment by Plypy** [comment]
I have encountered this error several times as well. On my machine this can be solved by updating `lodash`. However, the `npm-shrinkwrap.json`, which will lock up the version of dependencies, can block the updating... You know, I usually do my development with this file removed. 

Maybe we could only use `npm-shrinkwrap.json` in production branch. Since current `npm-shrinkwrap.json` don't have much meaning, I think we could delete it from the branch `gsoc-2015` and `master`.

**Comment by Plypy** [comment]
Please re-pull this... I've fixed some bugs.

**Comment by robbyoconnor** [comment]
We should probably fix the shrinkwrap file to keep in line with the versions in package.json

**Comment by Plypy** [comment]
Removed it as it's only meaningful in stable version.

**Comment by robbyoconnor** [comment]
Your tests now pass -- but when registering I get this: 
```
No such groups
Error: No such groups at Promise.<anonymous> (/home/action/workspace/openmrs-contrib-id/app/model/user.js:453:19) at Promise.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8) at Promise.EventEmitter.emit (events.js:95:17) at Promise.emit (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38) at Promise.fulfill (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20) at cb (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/lib/query.js:1569:22) at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/lib/utils.js:408:16 at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:787:14 at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1195:7 at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1903:9 at Server.Base._callHandler (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41) at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18 at MongoReply.parseBody (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) at null.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20) at EventEmitter.emit (events.js:95:17) at null.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13) at EventEmitter.emit (events.js:98:17) at Socket.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22) at Socket.EventEmitter.emit (events.js:95:17) at Socket.<anonymous> (_stream_readable.js:746:14) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10) at TCP.onread (net.js:528:21)
```

**Comment by robbyoconnor** [comment]
Okay, now your tests pass (great job with that) but I can not login now! 

Here's the error:

Error: No such groups at Promise.<anonymous> (/home/action/workspace/openmrs-contrib-id/app/model/user.js:453:19) at Promise.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8) at Promise.EventEmitter.emit (events.js:95:17) at Promise.emit (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38) at Promise.fulfill (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20) at cb (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/lib/query.js:1569:22) at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/lib/utils.js:408:16 at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:787:14 at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1195:7 at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1903:9 at Server.Base._callHandler (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41) at /home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18 at MongoReply.parseBody (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) at null.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20) at EventEmitter.emit (events.js:95:17) at null.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13) at EventEmitter.emit (events.js:98:17) at Socket.<anonymous> (/home/action/workspace/openmrs-contrib-id/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22) at Socket.EventEmitter.emit (events.js:95:17) at Socket.<anonymous> (_stream_readable.js:746:14) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10) at TCP.onread (net.js:528:21)

Here's the error: 

TypeError: undefined is not a function
    at findLDAP (/home/action/workspace/openmrs-contrib-id/app/model/user.js:352:5)
    at fn (/home/action/workspace/openmrs-contrib-id/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/home/action/workspace/openmrs-contrib-id/node_modules/async/lib/async.js:498:34)

Which is [this](https://github.com/Plypy/openmrs-contrib-id/blob/ID-89/app/model/user.js#L352); prior to your PR, things worked...

It also fails when logging in as well

**Comment by Plypy** [comment]
...... So sorry..... Forgot to update this outdated code... Forgot to do the system test...

**Comment by robbyoconnor** [comment]
Please fix it before Monday -- if you don't mind updating that code -- you can leave the rest of your work for Monday -- I'm using Nitrious.io Lite (it's being torpedoed on July 1 -- but I was stumbling too much to set up openldap in vagrant)

We really should also have tests, but I'm really going to be strict on this and not budge -- but it's the second half's milestone, not midterm...you've done a fantastic job thus far :) 

There is no need to squash it into one tidt commit (though I'd like that)-- it's fine if you don't (in this case)

**Comment by Plypy** [comment]
Fixed, have a look.

**Comment by robbyoconnor** [comment]
:+1: Works for me now. Great work

**Comment by robbyoconnor** [comment]
Good job :)

**Pull request merged**
