### PR TITLE
GCI-31 Change buttons in NavBar

### PR DESCRIPTION
**Pull request by itatriev**
Well, I changed the type of button so it's corresponds buttons below (btn-success), size, frame(increase padding scale).. You can see it on the screen below -->
selection_018

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Great start! Looks amazing...but a few comments...this isn't a 100% acceptable solution in my eyes: 

Using [Bootstrap Breadcumbs](http://getbootstrap.com/components/#breadcrumbs) is the better approach...and possibly having a look at the [Bootstrap Navbar](http://getbootstrap.com/components/#navbar) as well (in addition to)...this is great work...just not entirely correct. 

@elliottwilliams  probably has more comments but this is what I see as necessary to close this task...implementing these would be sufficient for me.

**Comment by elliottwilliams** [comment]
@itatriev this pull request needs to be open if you want it reviewed :-)

Please re-open if you're still planning on working on it. Thanks!

**Comment by elliottwilliams** [comment]
I'm actually quite happy with this, you definitely stuck to the requested design and I think it looks really good.

(Rationale) To me, it makes sense not Bootstrap breadcrumbs, since there's no hierarchical data here, just 2-4 links that move between major functions of the ID Dashboard. Using a navbar unit would have been okay, but it adds unneeded markup and visual complexity. Thanks for your work, and if @robbyoconnor is okay as well I'll accept the task.

**Comment by robbyoconnor** [comment]
I wish you linked to the task, which task was this?

**Pull request merged**
